spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/db_ms_auth
    platform: postgres
    password: root
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  database:
    driverClassName: org.postgresql.Driver
