spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/db_ms_base
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: 'true'
    hibernate:
      ddl-auto: update
