spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://ms-user-pg14:5432/db_ms_user
    platform: postgres
    password: 1234567
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: update
    show-sql: false
  database:
    driverClassName: org.postgresql.Driver
